#pragma once
#ifndef CATA_SRC_BLOCK3D_ATLAS_H
#define CATA_SRC_BLOCK3D_ATLAS_H

// Embedded built-in sprite/texture atlases for the block_3d renderer, so the
// 3D view always has real entity and terrain art regardless of the install
// layout or which tileset (if any) is present. The arrays are PNG bytes,
// generated by tools/gfx/gen_block3d_sprites.py (which also writes preview
// copies to gfx/Block3D/ for humans).

extern const unsigned char block3d_entities_png[];
extern const unsigned int block3d_entities_png_len;
extern const unsigned char block3d_terrain_png[];
extern const unsigned int block3d_terrain_png_len;

#endif // CATA_SRC_BLOCK3D_ATLAS_H
